CREATE TABLE `car` (
  `cid` INT(10) NOT NULL AUTO_INCREMENT,
  `branch` VARCHAR(20) DEFAULT NULL,
  `type` VARCHAR(20) DEFAULT NULL,
  `year` VARCHAR(20) DEFAULT NULL,
  `configure` VARCHAR(30) DEFAULT NULL,
  `size` VARCHAR(10) DEFAULT NULL,
  `fuel` VARCHAR(20) DEFAULT NULL,
  `gus` VARCHAR(20) DEFAULT NULL,
  `speed` VARCHAR(20) DEFAULT NULL,
  `drive` VARCHAR(20) DEFAULT NULL,
  `price` DOUBLE DEFAULT NULL,
  `picture` VARCHAR(528) DEFAULT NULL,
  `status` VARCHAR(20) DEFAULT '正常',
  `GPS` VARCHAR(10) DEFAULT NULL,
  `amount` INT(10) DEFAULT NULL,
  PRIMARY KEY (`cid`)
) ENGINE=INNODB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8

