CREATE TABLE `user` (
  `uid` INT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `real_name` VARCHAR(20) DEFAULT NULL,
  `license` VARCHAR(20) DEFAULT NULL,
  `id_card` VARCHAR(20) DEFAULT NULL,
  `tel` VARCHAR(25) DEFAULT NULL,
  `email` VARCHAR(20) DEFAULT NULL,
  `address` VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (`uid`),
  UNIQUE KEY `name` (`name`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8
DB DEFAULT CHARSET=utf8